---
pipeline:
  split_sizes: 1,2,4,8,16,32,64
  options:
    offload: true
  setups:
    GPipe: 
      placement: 0,1,2,3
      schedule: afab
    1f1b:
      placement: 0,1,2,3
      schedule: 1f1b
    Megatron-LM:
      placement: 0,1,2,3,0,1,2,3
      schedule: 1f1b
    Hanayo 1-Wave:
      placement: 0,1,2,3,3,2,1,0
      schedule: hanayo
    Hanayo 2-Waves:
      placement: 0,1,2,3,3,2,1,0,0,1,2,3,3,2,1,0
      schedule: hanayo
    Hanayo 3-Waves:
      placement: 0,1,2,3,3,2,1,0,0,1,2,3,3,2,1,0,0,1,2,3,3,2,1,0
      schedule: hanayo
model:
  arch: GPT
  conf: GPTLargeConfig
  vocab_size: 3072
  batch_size: 64
  block_size: 64
iters: 15
warmups: 1