executor: slurm

default-resources:
  - runtime=60
  - constraint=h100
  - output=out.slurm
  - error=err.slurm
  - account=hyb@h100

# Ensure localrules stay local even when using the Slurm executor
local-cores: 1
jobs: 4

keep-incomplete: true # benchmarks write a file containing "error: OOM" if they fail to indicate that there is no need to rerun them. keep that file