default: &DEFAULT
  verbose: True
  data:
    dataset_name: 'c4realnewslike'
    cifar10:
      dataset_dir: "/net/storage/pr3/project/tutorial/elf/data/cifar10"
      load_dataset: false  
    c4realnewslike:
      dataset_dir: "/net/storage/pr3/project/tutorial/elf/data/c4-realnewslike"
      load_dataset: false